export const categories = [
  {
    id: 'general-knowledge',
    name: 'General Knowledge',
    description: 'Trivia, current affairs, and broad learning',
    icon: '🌍',
    questions: 50,
    difficulty: 'Medium',
    attempts: 1248,
    color: '#7c3aed',
  },
  {
    id: 'computer-science',
    name: 'Computer Science',
    description: 'Algorithms, systems, and fundamentals',
    icon: '💻',
    questions: 60,
    difficulty: 'Medium',
    attempts: 980,
    color: '#2563eb',
  },
  {
    id: 'programming',
    name: 'Programming',
    description: 'Coding skills, syntax, and problem solving',
    icon: '🧠',
    questions: 45,
    difficulty: 'Hard',
    attempts: 1204,
    color: '#14b8a6',
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    description: 'Logic, arithmetic, algebra, and reasoning',
    icon: '📐',
    questions: 55,
    difficulty: 'Medium',
    attempts: 730,
    color: '#f59e0b',
  },
  {
    id: 'science',
    name: 'Science',
    description: 'Physics, biology, chemistry, and experiments',
    icon: '🔬',
    questions: 40,
    difficulty: 'Medium',
    attempts: 812,
    color: '#10b981',
  },
  {
    id: 'history',
    name: 'History',
    description: 'World events, civilizations, and leaders',
    icon: '🏛️',
    questions: 48,
    difficulty: 'Easy',
    attempts: 501,
    color: '#ef4444',
  },
  {
    id: 'geography',
    name: 'Geography',
    description: 'Countries, capitals, and places',
    icon: '🌎',
    questions: 35,
    difficulty: 'Easy',
    attempts: 443,
    color: '#0ea5e9',
  },
  {
    id: 'current-affairs',
    name: 'Current Affairs',
    description: 'Latest news and national events',
    icon: '📰',
    questions: 42,
    difficulty: 'Hard',
    attempts: 689,
    color: '#ec4899',
  },
  {
    id: 'english',
    name: 'English',
    description: 'Grammar, vocabulary, and comprehension',
    icon: '📚',
    questions: 52,
    difficulty: 'Easy',
    attempts: 962,
    color: '#f97316',
  },
  {
    id: 'aptitude',
    name: 'Aptitude',
    description: 'Analytical reasoning and speed tests',
    icon: '⚡',
    questions: 58,
    difficulty: 'Hard',
    attempts: 1160,
    color: '#22c55e',
  },
]

export const sampleQuizzes = [
  {
    id: 'cs-fundamentals',
    title: 'Computer Science Fundamentals',
    description: 'Test your understanding of core programming and CS concepts.',
    category: 'Computer Science',
    difficulty: 'Medium',
    timeLimit: 12,
    totalMarks: 20,
    passingPercentage: 70,
    questions: [
      {
        id: 1,
        question: 'Which programming language is primarily used for web development?',
        options: ['JavaScript', 'Python', 'C++', 'Java'],
        correctAnswer: 'JavaScript',
        explanation: 'JavaScript is the core language used to build interactive behavior in web applications.',
        marks: 1,
      },
      {
        id: 2,
        question: 'What does HTML stand for?',
        options: [
          'HyperText Markup Language',
          'HighText Machine Language',
          'Hyperlink Technical Model Language',
          'Home Tool Markup Language',
        ],
        correctAnswer: 'HyperText Markup Language',
        explanation: 'HTML is the standard markup language used to structure content on the web.',
        marks: 1,
      },
      {
        id: 3,
        question: 'Which data structure uses FIFO ordering?',
        options: ['Stack', 'Queue', 'Tree', 'Graph'],
        correctAnswer: 'Queue',
        explanation: 'A queue processes elements in the order they were inserted, which is FIFO.',
        marks: 1,
      },
      {
        id: 4,
        question: 'What is the main purpose of an operating system?',
        options: [
          'To design websites',
          'To manage computer hardware and software resources',
          'To compile Java programs',
          'To store data in the cloud',
        ],
        correctAnswer: 'To manage computer hardware and software resources',
        explanation: 'Operating systems coordinate hardware access and provide a platform for running software.',
        marks: 1,
      },
      {
        id: 5,
        question: 'Which of the following is a relational database?',
        options: ['MongoDB', 'Redis', 'MySQL', 'Cassandra'],
        correctAnswer: 'MySQL',
        explanation: 'MySQL is a classic relational database management system based on tables and SQL.',
        marks: 1,
      },
    ],
  },
  {
    id: 'programming-basics',
    title: 'Programming Basics',
    description: 'Sharpen your coding knowledge with syntax and logic questions.',
    category: 'Programming',
    difficulty: 'Easy',
    timeLimit: 10,
    totalMarks: 15,
    passingPercentage: 60,
    questions: [
      {
        id: 1,
        question: 'Which keyword is used to declare a constant in JavaScript?',
        options: ['let', 'var', 'const', 'static'],
        correctAnswer: 'const',
        explanation: 'const declares a block-scoped variable whose value cannot be reassigned.',
        marks: 1,
      },
      {
        id: 2,
        question: 'What does CSS control?',
        options: ['Database logic', 'Page styling', 'Server routing', 'API calls'],
        correctAnswer: 'Page styling',
        explanation: 'CSS defines the presentation and layout of HTML content.',
        marks: 1,
      },
      {
        id: 3,
        question: 'Which loop executes at least once?',
        options: ['for', 'while', 'do...while', 'if'],
        correctAnswer: 'do...while',
        explanation: 'A do...while loop evaluates the condition after the loop body executes at least once.',
        marks: 1,
      },
      {
        id: 4,
        question: 'What is a function parameter?',
        options: ['A return value', 'A local variable', 'A value passed into the function', 'A keyword'],
        correctAnswer: 'A value passed into the function',
        explanation: 'Parameters are variables used to receive values the function needs to work with.',
        marks: 1,
      },
      {
        id: 5,
        question: 'Which data type is used for true/false values?',
        options: ['String', 'Number', 'Boolean', 'Object'],
        correctAnswer: 'Boolean',
        explanation: 'Boolean values represent logical truth and are either true or false.',
        marks: 1,
      },
    ],
  },
  {
    id: 'mathematics-essentials',
    title: 'Mathematics Essentials',
    description: 'Solve arithmetic and algebra challenges with confidence.',
    category: 'Mathematics',
    difficulty: 'Medium',
    timeLimit: 15,
    totalMarks: 20,
    passingPercentage: 65,
    questions: [
      {
        id: 1,
        question: 'Solve: 12 × 8 ÷ 2',
        options: ['24', '48', '96', '36'],
        correctAnswer: '48',
        explanation: 'Multiplication and division are performed left to right: 12 × 8 = 96, then 96 ÷ 2 = 48.',
        marks: 1,
      },
      {
        id: 2,
        question: 'What is 15% of 200?',
        options: ['20', '25', '30', '35'],
        correctAnswer: '30',
        explanation: '15% of 200 is 0.15 × 200 = 30.',
        marks: 1,
      },
      {
        id: 3,
        question: 'Simplify: 3x + 2x - 5 = 10',
        options: ['x = 3', 'x = 2', 'x = 5', 'x = 7'],
        correctAnswer: 'x = 3',
        explanation: '5x = 15, so x = 3.',
        marks: 1,
      },
      {
        id: 4,
        question: 'Which number is a prime number?',
        options: ['21', '27', '29', '33'],
        correctAnswer: '29',
        explanation: '29 has no divisors other than 1 and itself.',
        marks: 1,
      },
      {
        id: 5,
        question: 'What is the perimeter of a rectangle with sides 6 and 4?',
        options: ['10', '20', '24', '28'],
        correctAnswer: '20',
        explanation: 'Perimeter = 2(6 + 4) = 20.',
        marks: 1,
      },
    ],
  },
  {
    id: 'general-knowledge-lite',
    title: 'General Knowledge Challenge',
    description: 'A balanced mix of world facts and everyday knowledge.',
    category: 'General Knowledge',
    difficulty: 'Easy',
    timeLimit: 10,
    totalMarks: 15,
    passingPercentage: 60,
    questions: [
      {
        id: 1,
        question: 'Which planet is known as the Red Planet?',
        options: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
        correctAnswer: 'Mars',
        explanation: 'Mars looks red because its surface is rich in iron oxide, or rust.',
        marks: 1,
      },
      {
        id: 2,
        question: 'Which language has the most native speakers worldwide?',
        options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'],
        correctAnswer: 'Mandarin Chinese',
        explanation: 'Mandarin Chinese has the largest number of native speakers in the world.',
        marks: 1,
      },
      {
        id: 3,
        question: 'What is the capital of Japan?',
        options: ['Seoul', 'Osaka', 'Tokyo', 'Kyoto'],
        correctAnswer: 'Tokyo',
        explanation: 'Tokyo is the capital of Japan and its largest city.',
        marks: 1,
      },
      {
        id: 4,
        question: 'Which ocean is the largest on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'],
        correctAnswer: 'Pacific Ocean',
        explanation: 'The Pacific is the world’s largest and deepest ocean.',
        marks: 1,
      },
      {
        id: 5,
        question: 'Who wrote the play “Hamlet”?',
        options: ['Charles Dickens', 'Jane Austen', 'William Shakespeare', 'Oscar Wilde'],
        correctAnswer: 'William Shakespeare',
        explanation: 'Hamlet is one of Shakespeare’s most famous tragedies.',
        marks: 1,
      },
    ],
  },
  {
    id: 'science-spotlight',
    title: 'Science Spotlight',
    description: 'Discover key principles from chemistry, biology, and physics.',
    category: 'Science',
    difficulty: 'Hard',
    timeLimit: 18,
    totalMarks: 20,
    passingPercentage: 70,
    questions: [
      {
        id: 1,
        question: 'What is the chemical symbol for gold?',
        options: ['Gd', 'Go', 'Au', 'Ag'],
        correctAnswer: 'Au',
        explanation: 'The symbol Au comes from the Latin word aurum, which means gold.',
        marks: 1,
      },
      {
        id: 2,
        question: 'Which organ is responsible for pumping blood throughout the body?',
        options: ['Lungs', 'Kidneys', 'Liver', 'Heart'],
        correctAnswer: 'Heart',
        explanation: 'The heart pumps oxygenated blood through the circulatory system.',
        marks: 1,
      },
      {
        id: 3,
        question: 'Which force keeps planets in orbit around the sun?',
        options: ['Magnetism', 'Gravity', 'Friction', 'Pressure'],
        correctAnswer: 'Gravity',
        explanation: 'Gravity is the force that attracts masses together and keeps planets in orbit.',
        marks: 1,
      },
      {
        id: 4,
        question: 'What is the boiling point of water at sea level?',
        options: ['90°C', '100°C', '110°C', '120°C'],
        correctAnswer: '100°C',
        explanation: 'At standard atmospheric pressure, water boils at 100°C.',
        marks: 1,
      },
      {
        id: 5,
        question: 'Which part of a plant absorbs water from the soil?',
        options: ['Leaf', 'Stem', 'Root', 'Flower'],
        correctAnswer: 'Root',
        explanation: 'Roots absorb water and minerals from the soil and anchor the plant.',
        marks: 1,
      },
    ],
  },
]

export const leaderboardData = [
  { rank: 1, name: 'Ariana Lee', points: 9230, quizzes: 82, accuracy: 96, badge: '🏆' },
  { rank: 2, name: 'David Moore', points: 9015, quizzes: 79, accuracy: 94, badge: '🥈' },
  { rank: 3, name: 'Priya Nair', points: 8850, quizzes: 74, accuracy: 93, badge: '🥉' },
  { rank: 4, name: 'Sophia Chen', points: 8425, quizzes: 71, accuracy: 92, badge: '🎯' },
  { rank: 5, name: 'Marcus Hill', points: 8120, quizzes: 68, accuracy: 89, badge: '🔥' },
  { rank: 6, name: 'Ava Johnson', points: 7880, quizzes: 64, accuracy: 87, badge: '⭐' },
  { rank: 7, name: 'Noah Patel', points: 7605, quizzes: 61, accuracy: 86, badge: '💡' },
]

export const recentActivity = [
  { name: 'Computer Science Fundamentals', date: '2026-09-12', score: 18, percentage: 90, status: 'Completed' },
  { name: 'General Knowledge Challenge', date: '2026-09-10', score: 14, percentage: 93, status: 'Completed' },
  { name: 'Programming Basics', date: '2026-09-08', score: 11, percentage: 73, status: 'In Progress' },
  { name: 'Mathematics Essentials', date: '2026-09-05', score: 16, percentage: 84, status: 'Completed' },
]

export const adminUsers = [
  { id: 1, name: 'Ava Johnson', email: 'ava@example.com', role: 'User', status: 'Active', joinDate: '2025-02-01' },
  { id: 2, name: 'Liam Scott', email: 'liam@example.com', role: 'Admin', status: 'Active', joinDate: '2024-11-19' },
  { id: 3, name: 'Mila Patel', email: 'mila@example.com', role: 'User', status: 'Blocked', joinDate: '2025-05-30' },
  { id: 4, name: 'Ethan Brooks', email: 'ethan@example.com', role: 'User', status: 'Active', joinDate: '2025-07-11' },
]

export const userProfile = {
  fullName: 'Ava Johnson',
  email: 'ava.johnson@example.com',
  joinDate: 'January 12, 2025',
  totalQuizzes: 42,
  totalPoints: 7880,
  averageScore: 87,
  bestScore: 98,
  streak: 7,
  rank: 6,
}

export const analyticsData = {
  lineData: [
    { name: 'Jan', score: 60 },
    { name: 'Feb', score: 72 },
    { name: 'Mar', score: 68 },
    { name: 'Apr', score: 81 },
    { name: 'May', score: 88 },
    { name: 'Jun', score: 90 },
    { name: 'Jul', score: 93 },
  ],
  barData: [
    { name: 'Math', correct: 18, incorrect: 6 },
    { name: 'CS', correct: 16, incorrect: 8 },
    { name: 'Science', correct: 14, incorrect: 10 },
    { name: 'English', correct: 15, incorrect: 7 },
  ],
  pieData: [
    { name: 'Correct', value: 72 },
    { name: 'Incorrect', value: 28 },
  ],
}
